export const REQUEST_JOB = 'REQUEST_JOB';
export const REQUEST_JOB_SUCCESS = 'REQUEST_JOB_SUCESS';

export const REQUEST_SKILL = 'REQUEST_SKILL';
export const REQUEST_SKILL_SUCCESS = 'REQUEST_SKILL_SUCCESS';
